GPUS: (0,)
OUTPUT_DIR: 'gcn_output'
LOG_DIR: 'gcn_log'
PERF_FNAME: 'train_perf_gcn'
WORKERS: 8
PRINT_FREQ: 25

CUDNN:
  BENCHMARK: true
  DETERMINISTIC: false
  ENABLED: true

DATASET:
  ROOT: '../HRNet_old/data/contour_data/'

MODEL:
  NUM_NODES: 63
  NODE_FEATURE_DIM: 128
  IN_DIM: 192
  IN_CHANNEL: 256
  IMAGE_SIZE:
    - 256
    - 192
  NUM_JOINTS: 65
  GNN_TYPE: 'GCN'

TRAIN:
  BATCH_SIZE_PER_GPU: 16
  BEGIN_EPOCH: 0
  END_EPOCH: 1000
  OPTIMIZER: adam
  LR: 0.001
  LR_FACTOR: 0.1
  WD: 0.0001
  SIZE: 31688

TEST:
  BATCH_SIZE_PER_GPU: 32
  SIZE: 5941